site_name: WSIMOD docs

theme:
  name: "material"
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css


plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true
      ignore: ["./docs/create_class_page.py"]
  - search
  - bibtex:
      bib_file: "./docs/paper/paper.bib"
      csl_file: "./docs/paper/apa.csl"
      cite_inline: false
  - coverage:
      page_name: coverage  # default
      html_report_dir: htmlcov  # default
  - gen-files:
      scripts:
        - docs/create_class_page.py

repo_url: https://github.com/ImperialCollegeLondon/wsi
site_url: https://imperialcollegelondon.github.io/wsi/

markdown_extensions:
  - footnotes

nav:
  - Home: index.md
  - About: ./paper/paper.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - How to guide: how-to.md
  - Component library: component-library.md
  - Command line interface: wsimod-cli.md
  - Run WSIMOD in DAFNI: dafni.md
  - API reference: reference.md
  - Quickstart: ./demo/scripts/quickstart_demo.py
  - Coverage report: coverage.md
  - WSIMOD repository: https://github.com/barneydobson/wsi