site_name: WSIMOD docs

theme:
  name: "material"

extra_css:
  - stylesheets/extra.css


plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true
  - search
  
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - How to guide: how-to.md
  - API reference: reference.md
  - Quickstart: ./demo/scripts/quickstart_demo.py