site_name: WSIMOD docs

theme:
  name: "material"

extra_css:
  - stylesheets/extra.css


plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true
  - search
  - bibtex:
      bib_file: "./docs/paper/paper.bib"
      csl_file: "./docs/paper/apa.csl"
      cite_inline: false
      
markdown_extensions:
  - footnotes

nav:
  - Home: index.md
  - About: ./paper/paper.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - How to guide: how-to.md
  - API reference: reference.md
  - Quickstart: ./demo/scripts/quickstart_demo.py