import setuptools

setuptools.setup(
   name='WSIMOD',
   version='0.1',
   author='Barnaby Dobson',
   author_email='b.dobson@imperial.ac.uk',
   packages=setuptools.find_packages(),
   license='LICENSE.txt',
   description='WSIMOD is for simulating water quality and quantity',
   long_description=open('README.md').read(),
   install_requires=['pandas',
      'geopandas',
      'dill',
      'matplotlib',
      'gitpython',
      'numpy',
      'ukcensusapi',
      'xarray',
      'OSGridConverter',
      'shapely',
      'snkit',
      'networkx',
      'rasterio',
      'tqdm',
      'requests',
      'pytest',
      'pyarrow',
      'fastparquet'
      ],
      )
